[env]
_.file = ".env.secrets"
_.python.venv = { path = ".venv", create = true }

DJANGO_DEBUG = "true"

[tools]
python = "3.13"

[tasks.dev]
description = "Run the development server"
run = "python manage.py runserver"

[tasks.format]
description = "Run the formatter [and modify files]"
run = "ruff format {{arg(name='dir', default='.')}}"

[tasks.lint]
description = "Run the linter [and modify files]"
run = "ruff check --fix {{arg(name='dir', default='.')}}"

[tasks.typecheck]
description = "Run the basedpyright type checker"
run = "basedpyright --level error {{arg(name='dir', default='.')}}"
