[env]
_.file = ".env.secrets"

[tools]
python = "3.13"

[tasks.format]
description = "Run the formatter [and modify files]"
run = "ruff format {{arg(name='dir', default='.')}}"

[tasks.lint]
description = "Run the linter [and modify files]"
run = "ruff check --fix {{arg(name='dir', default='.')}}"

[tasks.typecheck]
description = "Run the basedpyright type checker"
run = "basedpyright {{arg(name='dir', default='.')}}"
