# Generated by Django 5.2.6 on 2025-09-08 02:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geologger', '0001_add_jobsite_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('last_location', django.contrib.gis.db.models.fields.PointField(blank=True, editable=False, null=True, srid=4326)),
            ],
        ),
    ]
