# Generated by Django 5.2.6 on 2025-09-08 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geologger', '0002_add_technician_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('job_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geologger.jobsite')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geologger.technician')),
            ],
        ),
    ]
